{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.gradle.classplugin",
    "module": "hive-class-guard",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.4.jar",
          "url": "hive-class-guard-2.0.4.jar",
          "size": 127864,
          "sha512": "1be3a54eebcf71b212b93fcd45d3b434e4c941b29814fa4b8a52d0fa7f26eb24d305c9f4577993c8f8e7b049884a980671783d3a4caa0f9b42ba0e037843ec6e",
          "sha256": "322c15153223624bee05506fd654254ccbd03bf327c74f097fb5bb3f2a175e66",
          "sha1": "b4f3aca3c652937f39a9bf6417200824631ff9d4",
          "md5": "7fa22da082551fe50f822914fed8ff07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.4.jar",
          "url": "hive-class-guard-2.0.4.jar",
          "size": 127864,
          "sha512": "1be3a54eebcf71b212b93fcd45d3b434e4c941b29814fa4b8a52d0fa7f26eb24d305c9f4577993c8f8e7b049884a980671783d3a4caa0f9b42ba0e037843ec6e",
          "sha256": "322c15153223624bee05506fd654254ccbd03bf327c74f097fb5bb3f2a175e66",
          "sha1": "b4f3aca3c652937f39a9bf6417200824631ff9d4",
          "md5": "7fa22da082551fe50f822914fed8ff07"
        }
      ]
    }
  ]
}
