{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.gradle.classplugin",
    "module": "hive-class-guard",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.4.jar",
          "url": "hive-class-guard-2.0.4.jar",
          "size": 124300,
          "sha512": "17385ef9f7356968f7b4dce47dfebdd09ed874545bae5bed143451ae7c1b564fda255b0808bd47a39be3881fc32270fe3fb7f15c3c0c40382d21743a86bb4681",
          "sha256": "4b691020aa0bb2f46c866c8d2f620d268807cddebb1bf050d1adafdf0bdd9a62",
          "sha1": "7bee83a1a95cf92f1fbabadf15e9ca1fc1b1f050",
          "md5": "01223c48aa2ba5c85d636b60719d7741"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.4.jar",
          "url": "hive-class-guard-2.0.4.jar",
          "size": 124300,
          "sha512": "17385ef9f7356968f7b4dce47dfebdd09ed874545bae5bed143451ae7c1b564fda255b0808bd47a39be3881fc32270fe3fb7f15c3c0c40382d21743a86bb4681",
          "sha256": "4b691020aa0bb2f46c866c8d2f620d268807cddebb1bf050d1adafdf0bdd9a62",
          "sha1": "7bee83a1a95cf92f1fbabadf15e9ca1fc1b1f050",
          "md5": "01223c48aa2ba5c85d636b60719d7741"
        }
      ]
    }
  ]
}
