{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.native",
    "module": "libNative",
    "version": "null-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libNative-null-SNAPSHOT.aar",
          "url": "libNative-null-SNAPSHOT.aar",
          "size": 21484,
          "sha512": "350896cf8bcedcd96e5b0a69b77768bb3b3078732629582eaf604541bfe4c7ef59caa5c7168ea98a561cf4f2e9b6a29390cab7c21c1f19067269f5b1e5f40a29",
          "sha256": "74c509207b8e69784b4adb0cb6bcd8e2dd4fd7e74812843f230047bad25addd8",
          "sha1": "aafaf1eda8441aad43c0eb4a2b7e2a1044b71f70",
          "md5": "f9d01f8f6093988c8afed05ccc938d40"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libNative-null-SNAPSHOT.aar",
          "url": "libNative-null-SNAPSHOT.aar",
          "size": 21484,
          "sha512": "350896cf8bcedcd96e5b0a69b77768bb3b3078732629582eaf604541bfe4c7ef59caa5c7168ea98a561cf4f2e9b6a29390cab7c21c1f19067269f5b1e5f40a29",
          "sha256": "74c509207b8e69784b4adb0cb6bcd8e2dd4fd7e74812843f230047bad25addd8",
          "sha1": "aafaf1eda8441aad43c0eb4a2b7e2a1044b71f70",
          "md5": "f9d01f8f6093988c8afed05ccc938d40"
        }
      ]
    }
  ]
}
