{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.cocos2",
    "module": "libCocos2",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCocos2-2.0.0-SNAPSHOT.aar",
          "url": "libCocos2-2.0.0-SNAPSHOT.aar",
          "size": 18790216,
          "sha512": "cf17b59fac42bd27558ba6f28686972e0463660139bd3efcd58987e0be689537b53b3ca956db1dce52e905163d2f71d321abf7ff3cd36cefdc528d309b65e0e8",
          "sha256": "4b94a0fda56e1e4070a810786a74a0ce517d4be6c6c532691a32b24b1231be1d",
          "sha1": "f60dff1b4f831ee643b53820a552feb609469fdc",
          "md5": "5fb99eeba3872b9dc07cfe5e46135fbb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libCocos2-2.0.0-SNAPSHOT.aar",
          "url": "libCocos2-2.0.0-SNAPSHOT.aar",
          "size": 18790216,
          "sha512": "cf17b59fac42bd27558ba6f28686972e0463660139bd3efcd58987e0be689537b53b3ca956db1dce52e905163d2f71d321abf7ff3cd36cefdc528d309b65e0e8",
          "sha256": "4b94a0fda56e1e4070a810786a74a0ce517d4be6c6c532691a32b24b1231be1d",
          "sha1": "f60dff1b4f831ee643b53820a552feb609469fdc",
          "md5": "5fb99eeba3872b9dc07cfe5e46135fbb"
        }
      ]
    }
  ]
}
