{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.reader",
    "module": "libReader",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libReader-2.0.0-SNAPSHOT.aar",
          "url": "libReader-2.0.0-SNAPSHOT.aar",
          "size": 478006,
          "sha512": "58f8b80b5cc1e87aa298a042e9b71233fa0acac55db103d89210266d632646eaceb287d0089735d18435acc25efc0cb7282cd5f4be22850ec7290e323e99d411",
          "sha256": "5d8fec1f82dd6f618e13599ba8eac291a1008a05c844e77823b775ca2fefbb79",
          "sha1": "8319aa75aa2700c7f89efbabf97b6b7676c73597",
          "md5": "952dbaee406b3efe9333d5a4033ba4cd"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.image",
          "module": "libImage",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.basenative",
          "module": "libBaseNative",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.adv",
          "module": "libAdv",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "cn.wanghaomiao",
          "module": "JsoupXpath",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.github.gedoor",
          "module": "rhino-android",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "net.ricecode",
          "module": "string-similarity",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libReader-2.0.0-SNAPSHOT.aar",
          "url": "libReader-2.0.0-SNAPSHOT.aar",
          "size": 478006,
          "sha512": "58f8b80b5cc1e87aa298a042e9b71233fa0acac55db103d89210266d632646eaceb287d0089735d18435acc25efc0cb7282cd5f4be22850ec7290e323e99d411",
          "sha256": "5d8fec1f82dd6f618e13599ba8eac291a1008a05c844e77823b775ca2fefbb79",
          "sha1": "8319aa75aa2700c7f89efbabf97b6b7676c73597",
          "md5": "952dbaee406b3efe9333d5a4033ba4cd"
        }
      ]
    }
  ]
}
