{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.cocos2",
    "module": "libCocos2",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCocos2-1.0.1-SNAPSHOT.aar",
          "url": "libCocos2-1.0.1-SNAPSHOT.aar",
          "size": 18788267,
          "sha512": "4609b04bd3d7cd903e959405c7c532423221964f6403bc701633f76b8fd4bbe3d5c2f594932b5f888b5a478ba6888080582c0c7d32207e677b19624ecc01a6d6",
          "sha256": "2b1996e050df00be9d3190e91133febbd9b03a1cc132564c2a1f85cdbf7b280f",
          "sha1": "29624d92fa0971ed347d8cc8854839b356575361",
          "md5": "aadcde8681f150e8e34dadb2c7c8cabb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libCocos2-1.0.1-SNAPSHOT.aar",
          "url": "libCocos2-1.0.1-SNAPSHOT.aar",
          "size": 18788267,
          "sha512": "4609b04bd3d7cd903e959405c7c532423221964f6403bc701633f76b8fd4bbe3d5c2f594932b5f888b5a478ba6888080582c0c7d32207e677b19624ecc01a6d6",
          "sha256": "2b1996e050df00be9d3190e91133febbd9b03a1cc132564c2a1f85cdbf7b280f",
          "sha1": "29624d92fa0971ed347d8cc8854839b356575361",
          "md5": "aadcde8681f150e8e34dadb2c7c8cabb"
        }
      ]
    }
  ]
}
