{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.gradle.classplugin",
    "module": "hive-class-guard",
    "version": "2.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.6.jar",
          "url": "hive-class-guard-2.0.6.jar",
          "size": 135806,
          "sha512": "83fb9fd6716f61f09d6e57ad88990be9cf9a848ec64718811cece41b91135616f058357057f00bfee7a63383bb7d6ffaed69d8fa42aefe157cb445cc7ae74e8e",
          "sha256": "5deee98244974f45f8ddda9c62c1be336b634f2d319a0240483b886a94674d3a",
          "sha1": "d0c668bfbe6bd3914030fef300d23c9031a21f8f",
          "md5": "7dca5988d5379379f72d81daaf142ad1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.6.jar",
          "url": "hive-class-guard-2.0.6.jar",
          "size": 135806,
          "sha512": "83fb9fd6716f61f09d6e57ad88990be9cf9a848ec64718811cece41b91135616f058357057f00bfee7a63383bb7d6ffaed69d8fa42aefe157cb445cc7ae74e8e",
          "sha256": "5deee98244974f45f8ddda9c62c1be336b634f2d319a0240483b886a94674d3a",
          "sha1": "d0c668bfbe6bd3914030fef300d23c9031a21f8f",
          "md5": "7dca5988d5379379f72d81daaf142ad1"
        }
      ]
    }
  ]
}
