{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.push",
    "module": "libPush",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPush-1.0.1-SNAPSHOT.aar",
          "url": "libPush-1.0.1-SNAPSHOT.aar",
          "size": 31853,
          "sha512": "a2865578fcaf1971967e67e32932ce98605dfa339127113319a924af5060adc5d69e4ee079641066c7e2522ea8e210bd3b972fbd0fec5560f4f0aeabcf7df9fc",
          "sha256": "63134ca7a5d3e04e913575a4c618db81779411f18b856fb9a8f69ad9db118a00",
          "sha1": "16c9f8c99b25b2ca297e124a69700aeeac45c1ae",
          "md5": "e07d5ee5eb90e493c9e3c8f3b3186087"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "alicloud-httpdns",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "alicloud-utils",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "alicloud_beacon",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo-accs",
          "version": {
            "requires": "3.3.9.7-open"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo_networksdk",
          "version": {
            "requires": "3.5.5"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo_tlog",
          "version": {
            "requires": "3.0.0.17"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo_tnet4android",
          "version": {
            "requires": "3.1.14.9"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libPush-1.0.1-SNAPSHOT.aar",
          "url": "libPush-1.0.1-SNAPSHOT.aar",
          "size": 31853,
          "sha512": "a2865578fcaf1971967e67e32932ce98605dfa339127113319a924af5060adc5d69e4ee079641066c7e2522ea8e210bd3b972fbd0fec5560f4f0aeabcf7df9fc",
          "sha256": "63134ca7a5d3e04e913575a4c618db81779411f18b856fb9a8f69ad9db118a00",
          "sha1": "16c9f8c99b25b2ca297e124a69700aeeac45c1ae",
          "md5": "e07d5ee5eb90e493c9e3c8f3b3186087"
        }
      ]
    }
  ]
}
