{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.push",
    "module": "libPush",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPush-1.0.2-SNAPSHOT.aar",
          "url": "libPush-1.0.2-SNAPSHOT.aar",
          "size": 32132,
          "sha512": "30d358f978048de851fc05a9d1bf6a16e0679e06921edbf8ab04c0931b3a8febd78a3a39d4e21c59476944a3781d38ea11560152e15692ad49045d94587b3a3e",
          "sha256": "6cb02761c86561cebcb4dbff52694c7b1bae968805a5df0803f3a0103438da6d",
          "sha1": "9da600b7d84242dadb467ee9d73d77f1e92cebcc",
          "md5": "10e519ccb386167f915eb922f8157ea7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "alicloud-httpdns",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "alicloud-utils",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "alicloud_beacon",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo-accs",
          "version": {
            "requires": "3.3.9.7-open"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo_networksdk",
          "version": {
            "requires": "3.5.5"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo_tlog",
          "version": {
            "requires": "3.0.0.17"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo_tnet4android",
          "version": {
            "requires": "3.1.14.9"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libPush-1.0.2-SNAPSHOT.aar",
          "url": "libPush-1.0.2-SNAPSHOT.aar",
          "size": 32132,
          "sha512": "30d358f978048de851fc05a9d1bf6a16e0679e06921edbf8ab04c0931b3a8febd78a3a39d4e21c59476944a3781d38ea11560152e15692ad49045d94587b3a3e",
          "sha256": "6cb02761c86561cebcb4dbff52694c7b1bae968805a5df0803f3a0103438da6d",
          "sha1": "9da600b7d84242dadb467ee9d73d77f1e92cebcc",
          "md5": "10e519ccb386167f915eb922f8157ea7"
        }
      ]
    }
  ]
}
