{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.push",
    "module": "libPush",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPush-1.0.2-SNAPSHOT.aar",
          "url": "libPush-1.0.2-SNAPSHOT.aar",
          "size": 31852,
          "sha512": "bbc49241632e6b5007ebc0d0cb57965983981163f87296a1acb4b089e421ce92dfa0570041e33858ae950622c7a0fca3e3ed1d80bbb44d05af84815104215126",
          "sha256": "f88df80e86e90140be812136d2da7f8a416f90aa8a1729a73b33159b7c458382",
          "sha1": "7cbbf3291fa6e50c8ccf58576d86ec5b85b025a2",
          "md5": "fa4c059a97b86e3dc0fcf9a6a661e5ba"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "alicloud-httpdns",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "alicloud-utils",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "alicloud_beacon",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo-accs",
          "version": {
            "requires": "3.3.9.7-open"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo_networksdk",
          "version": {
            "requires": "3.5.5"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo_tlog",
          "version": {
            "requires": "3.0.0.17"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo_tnet4android",
          "version": {
            "requires": "3.1.14.9"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libPush-1.0.2-SNAPSHOT.aar",
          "url": "libPush-1.0.2-SNAPSHOT.aar",
          "size": 31852,
          "sha512": "bbc49241632e6b5007ebc0d0cb57965983981163f87296a1acb4b089e421ce92dfa0570041e33858ae950622c7a0fca3e3ed1d80bbb44d05af84815104215126",
          "sha256": "f88df80e86e90140be812136d2da7f8a416f90aa8a1729a73b33159b7c458382",
          "sha1": "7cbbf3291fa6e50c8ccf58576d86ec5b85b025a2",
          "md5": "fa4c059a97b86e3dc0fcf9a6a661e5ba"
        }
      ]
    }
  ]
}
