{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.utils",
    "module": "libUtils",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-no-op",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow-core",
          "version": {
            "requires": "4.2.4"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow",
          "version": {
            "requires": "4.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "libUtils-2.0.0-SNAPSHOT.aar",
          "url": "libUtils-2.0.0-SNAPSHOT.aar",
          "size": 379458,
          "sha512": "211cd0c1b37ac791f0815443678dae2e271ab70259e46cd1769422a2b21166c186a4c661ad72a36b6d3210d44628b1bb11afd65f725f0f758033036dd773f57d",
          "sha256": "629d032e3fe8de8bc7c8c76e3ac3860c11c16dcc708c57e9c135f583c0d3cd1b",
          "sha1": "a37900cea10aefaf9c8f2399ff1e0ba451b214cc",
          "md5": "6a876a8f21f8588aa84bcb499554e4c8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-no-op",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow-core",
          "version": {
            "requires": "4.2.4"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow",
          "version": {
            "requires": "4.2.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "libUtils-2.0.0-SNAPSHOT.aar",
          "url": "libUtils-2.0.0-SNAPSHOT.aar",
          "size": 379458,
          "sha512": "211cd0c1b37ac791f0815443678dae2e271ab70259e46cd1769422a2b21166c186a4c661ad72a36b6d3210d44628b1bb11afd65f725f0f758033036dd773f57d",
          "sha256": "629d032e3fe8de8bc7c8c76e3ac3860c11c16dcc708c57e9c135f583c0d3cd1b",
          "sha1": "a37900cea10aefaf9c8f2399ff1e0ba451b214cc",
          "md5": "6a876a8f21f8588aa84bcb499554e4c8"
        }
      ]
    }
  ]
}
