{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.native",
    "module": "libNative",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libNative-1.0.1-SNAPSHOT.aar",
          "url": "libNative-1.0.1-SNAPSHOT.aar",
          "size": 21477,
          "sha512": "d6b4474e404fad4e797f91365eeea51ecf4180c2c77fbe9f9131446e1fb84916cf6581f96a1f03fe9fa0d8de40abc9672a8d97259dcb3c51ca38f29778ee39e8",
          "sha256": "56d9823c2a7a8a78234de2eb85c7bf754db3551f3f44eea538d86a6e7ac83cc4",
          "sha1": "d04b2db1753f260aea98d85b0b3b70db76a4e4a5",
          "md5": "bb4d9e4d0ac9bafcdc38d24d5ff63515"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libNative-1.0.1-SNAPSHOT.aar",
          "url": "libNative-1.0.1-SNAPSHOT.aar",
          "size": 21477,
          "sha512": "d6b4474e404fad4e797f91365eeea51ecf4180c2c77fbe9f9131446e1fb84916cf6581f96a1f03fe9fa0d8de40abc9672a8d97259dcb3c51ca38f29778ee39e8",
          "sha256": "56d9823c2a7a8a78234de2eb85c7bf754db3551f3f44eea538d86a6e7ac83cc4",
          "sha1": "d04b2db1753f260aea98d85b0b3b70db76a4e4a5",
          "md5": "bb4d9e4d0ac9bafcdc38d24d5ff63515"
        }
      ]
    }
  ]
}
