{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.ocr",
    "module": "libOcr",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libOcr-2.0.0-SNAPSHOT.aar",
          "url": "libOcr-2.0.0-SNAPSHOT.aar",
          "size": 20926,
          "sha512": "6efffeecbb33ca1b90af2a31b06720908ca676fc2f4b8d3662c7d8a9bd021e6ea90c06e867459b2c73697f7f66d78081f7eeb5fc7c28ddfe38946662366eb498",
          "sha256": "4cd9aca1f6beb491dcc61321079d3d1cd3eb9be7f5984dd6d4566f2a0a905376",
          "sha1": "68e0303ca702a7ef35f9f30087acc512b2e1452c",
          "md5": "d5d23e277ce4fe208a7db8a0abc724d2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.basenative",
          "module": "libBaseNative",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.rmtheis",
          "module": "tess-two",
          "version": {
            "requires": "9.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libOcr-2.0.0-SNAPSHOT.aar",
          "url": "libOcr-2.0.0-SNAPSHOT.aar",
          "size": 20926,
          "sha512": "6efffeecbb33ca1b90af2a31b06720908ca676fc2f4b8d3662c7d8a9bd021e6ea90c06e867459b2c73697f7f66d78081f7eeb5fc7c28ddfe38946662366eb498",
          "sha256": "4cd9aca1f6beb491dcc61321079d3d1cd3eb9be7f5984dd6d4566f2a0a905376",
          "sha1": "68e0303ca702a7ef35f9f30087acc512b2e1452c",
          "md5": "d5d23e277ce4fe208a7db8a0abc724d2"
        }
      ]
    }
  ]
}
