{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.timer",
    "module": "libTimer",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libTimer-1.0.1-SNAPSHOT.aar",
          "url": "libTimer-1.0.1-SNAPSHOT.aar",
          "size": 88434,
          "sha512": "dbc3b8065d409ecd1f29cbb6850d6f172215ffb5d4da913123624036deaf0c84fa889efa58617b25ef5cf46191006c3539bbaf7dff7c62a93be09fc9821ef4fe",
          "sha256": "c0863bdfac92ecebfba4377aabc231ad3b1af1e7986b1e98148cf017c0f3e671",
          "sha1": "d0d5a7812ed8243d039fb317fdaff6719c97735f",
          "md5": "b009df365d60757658680adb625dae42"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.image",
          "module": "libImage",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libTimer-1.0.1-SNAPSHOT.aar",
          "url": "libTimer-1.0.1-SNAPSHOT.aar",
          "size": 88434,
          "sha512": "dbc3b8065d409ecd1f29cbb6850d6f172215ffb5d4da913123624036deaf0c84fa889efa58617b25ef5cf46191006c3539bbaf7dff7c62a93be09fc9821ef4fe",
          "sha256": "c0863bdfac92ecebfba4377aabc231ad3b1af1e7986b1e98148cf017c0f3e671",
          "sha1": "d0d5a7812ed8243d039fb317fdaff6719c97735f",
          "md5": "b009df365d60757658680adb625dae42"
        }
      ]
    }
  ]
}
