{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.adv",
    "module": "libAdv",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libAdv-1.0.2-SNAPSHOT.aar",
          "url": "libAdv-1.0.2-SNAPSHOT.aar",
          "size": 246620,
          "sha512": "282633318c750f1b7c11fc054c114cdb31cfd7e9fb1d653b110794bfb1013c2eaed8962717075d69ee21a049c924d0c88f2c712b844c8e1325feb2376325f478",
          "sha256": "968282f6d8696a21353a3bbbefa418f2fe3285b3d3e32d94353e7d7bef1582d5",
          "sha1": "6d643681914e462ba41fcf3692828032560c491e",
          "md5": "d3129a7175add3cd04ce79736369e67a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.image",
          "module": "libImage",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.basenative",
          "module": "libBaseNative",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "com.google.zxing",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.facebook.android",
          "module": "audience-network-sdk",
          "version": {
            "requires": "6.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "reward",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "interstitialvideo",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbnative",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbnativeadvanced",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "interstitial",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbbanner",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbsplash",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.adcolony",
          "module": "sdk",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "libAdv-1.0.2-SNAPSHOT.aar",
          "url": "libAdv-1.0.2-SNAPSHOT.aar",
          "size": 246620,
          "sha512": "282633318c750f1b7c11fc054c114cdb31cfd7e9fb1d653b110794bfb1013c2eaed8962717075d69ee21a049c924d0c88f2c712b844c8e1325feb2376325f478",
          "sha256": "968282f6d8696a21353a3bbbefa418f2fe3285b3d3e32d94353e7d7bef1582d5",
          "sha1": "6d643681914e462ba41fcf3692828032560c491e",
          "md5": "d3129a7175add3cd04ce79736369e67a"
        }
      ]
    }
  ]
}
