{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.clear",
    "module": "libClear",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libClear-1.0.1-SNAPSHOT.aar",
          "url": "libClear-1.0.1-SNAPSHOT.aar",
          "size": 34880,
          "sha512": "211f25aaab0d782a9f81583e65df191c5fc3fd34d878d060b7ee2230861970e7f4df5bfc0f1e798a1091f0b8921e0c9e9b3353351a3512e619d41e88e93d060e",
          "sha256": "0c3807c1ffd2db1147381a3f1e9c93c3901b8cf30a9f1acfeae4801edcfe5c85",
          "sha1": "8e8714e0bdc9077387120ae1c0934be5828a82b2",
          "md5": "6d774e37b8ef12d306d0165e6567bf94"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libClear-1.0.1-SNAPSHOT.aar",
          "url": "libClear-1.0.1-SNAPSHOT.aar",
          "size": 34880,
          "sha512": "211f25aaab0d782a9f81583e65df191c5fc3fd34d878d060b7ee2230861970e7f4df5bfc0f1e798a1091f0b8921e0c9e9b3353351a3512e619d41e88e93d060e",
          "sha256": "0c3807c1ffd2db1147381a3f1e9c93c3901b8cf30a9f1acfeae4801edcfe5c85",
          "sha1": "8e8714e0bdc9077387120ae1c0934be5828a82b2",
          "md5": "6d774e37b8ef12d306d0165e6567bf94"
        }
      ]
    }
  ]
}
