{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.adv",
    "module": "libAdv",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libAdv-1.0.3-SNAPSHOT.aar",
          "url": "libAdv-1.0.3-SNAPSHOT.aar",
          "size": 246640,
          "sha512": "1355a2d01f8c886309e47fd2e17aeb02b1b01e1432af7ce01b35ae3e91d30abb08c4e198b034cfde6214a6b5cfbce81612e58af820f7ec4f404b9a2e5b450edf",
          "sha256": "72270bf760ef0740e07deb1bc24582982489284af9e0cf262733711fddbf67f9",
          "sha1": "599a1405e9f7cc8719b6f843642c0525e97aef1f",
          "md5": "c11f6ca6f91ac0a7ab3628696fd84087"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.3-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.image",
          "module": "libImage",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.basenative",
          "module": "libBaseNative",
          "version": {
            "requires": "1.0.3-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "com.google.zxing",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.facebook.android",
          "module": "audience-network-sdk",
          "version": {
            "requires": "6.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "reward",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "interstitialvideo",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbnative",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbnativeadvanced",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "interstitial",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbbanner",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbsplash",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.adcolony",
          "module": "sdk",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "libAdv-1.0.3-SNAPSHOT.aar",
          "url": "libAdv-1.0.3-SNAPSHOT.aar",
          "size": 246640,
          "sha512": "1355a2d01f8c886309e47fd2e17aeb02b1b01e1432af7ce01b35ae3e91d30abb08c4e198b034cfde6214a6b5cfbce81612e58af820f7ec4f404b9a2e5b450edf",
          "sha256": "72270bf760ef0740e07deb1bc24582982489284af9e0cf262733711fddbf67f9",
          "sha1": "599a1405e9f7cc8719b6f843642c0525e97aef1f",
          "md5": "c11f6ca6f91ac0a7ab3628696fd84087"
        }
      ]
    }
  ]
}
