{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.player",
    "module": "libPlayer",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPlayer-1.0.3-SNAPSHOT.aar",
          "url": "libPlayer-1.0.3-SNAPSHOT.aar",
          "size": 9593344,
          "sha512": "a7630e019664f07db23bca6edd0c6f391f75fbb112486cee441dd60f82d91896a3c62072677c0d2cdeb9b223ea0bd748b2e16e1caf5785c958134575b85d39ef",
          "sha256": "20bba82245cb110bcd40a5f63df1e0bc60498a68348a9d1d64fa8e1884c95819",
          "sha1": "e7457b9c8f93b67253f300611c8151e1bdc5beae",
          "md5": "e2524f23d776f633147aaeede954734a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.image",
          "module": "libImage",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.basenative",
          "module": "libBaseNative",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "r1.5.11"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libPlayer-1.0.3-SNAPSHOT.aar",
          "url": "libPlayer-1.0.3-SNAPSHOT.aar",
          "size": 9593344,
          "sha512": "a7630e019664f07db23bca6edd0c6f391f75fbb112486cee441dd60f82d91896a3c62072677c0d2cdeb9b223ea0bd748b2e16e1caf5785c958134575b85d39ef",
          "sha256": "20bba82245cb110bcd40a5f63df1e0bc60498a68348a9d1d64fa8e1884c95819",
          "sha1": "e7457b9c8f93b67253f300611c8151e1bdc5beae",
          "md5": "e2524f23d776f633147aaeede954734a"
        }
      ]
    }
  ]
}
