{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.views",
    "module": "libViews",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libViews-1.0.2-SNAPSHOT.aar",
          "url": "libViews-1.0.2-SNAPSHOT.aar",
          "size": 523069,
          "sha512": "c0ee59a022e1d21cebebaa557f04294a6c521d20966ed595b9eaf51a51575bede96ae2c22d64799b977034fa42bca76d26f0d9dbc7f6a7c706303b49254b332c",
          "sha256": "accab847205afd02ce571104f5978d70cce2e56f86e8f03d384f88dcea5068b8",
          "sha1": "c81924d61759d62c71cd9de711a8f15dd35f1cc5",
          "md5": "bca01106dd49c7bb8e92a8f9cf58a8f7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.wang.avi",
          "module": "library",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "libViews-1.0.2-SNAPSHOT.aar",
          "url": "libViews-1.0.2-SNAPSHOT.aar",
          "size": 523069,
          "sha512": "c0ee59a022e1d21cebebaa557f04294a6c521d20966ed595b9eaf51a51575bede96ae2c22d64799b977034fa42bca76d26f0d9dbc7f6a7c706303b49254b332c",
          "sha256": "accab847205afd02ce571104f5978d70cce2e56f86e8f03d384f88dcea5068b8",
          "sha1": "c81924d61759d62c71cd9de711a8f15dd35f1cc5",
          "md5": "bca01106dd49c7bb8e92a8f9cf58a8f7"
        }
      ]
    }
  ]
}
