{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.views",
    "module": "libViews",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libViews-1.0.2-SNAPSHOT.aar",
          "url": "libViews-1.0.2-SNAPSHOT.aar",
          "size": 524888,
          "sha512": "92c375e2b34d70b3569c841ea2ccdfff4859d6284b9fce2cad316bdb7209b40f88477ec034ba99d210d79001610c5804b91527ae4da2a68de058e99a5ba2f26b",
          "sha256": "d5123c1b2b2d48a7be371518ae835ffa28e2f0afaf3e124a1d59792e819dc1ec",
          "sha1": "b657f1f3d972b116e88ce0c5cbe5ace4191f104e",
          "md5": "8141670e7e1c73f1278f7fc3a4a2b688"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.wang.avi",
          "module": "library",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "libViews-1.0.2-SNAPSHOT.aar",
          "url": "libViews-1.0.2-SNAPSHOT.aar",
          "size": 524888,
          "sha512": "92c375e2b34d70b3569c841ea2ccdfff4859d6284b9fce2cad316bdb7209b40f88477ec034ba99d210d79001610c5804b91527ae4da2a68de058e99a5ba2f26b",
          "sha256": "d5123c1b2b2d48a7be371518ae835ffa28e2f0afaf3e124a1d59792e819dc1ec",
          "sha1": "b657f1f3d972b116e88ce0c5cbe5ace4191f104e",
          "md5": "8141670e7e1c73f1278f7fc3a4a2b688"
        }
      ]
    }
  ]
}
