{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.views",
    "module": "libViews",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libViews-1.0.2-SNAPSHOT.aar",
          "url": "libViews-1.0.2-SNAPSHOT.aar",
          "size": 523076,
          "sha512": "d3fde4fa930fc64c196e0f9e008fa9c8e1640078cc6501818a291b0d41839a7708b6a82a13e991a0bab84839aaafb9bb7ca7e8441c4e3b9bdd1506550b146dca",
          "sha256": "3ea74852329fe78632ff461c485f3966afa20036eeca69540e9e32158b54b96e",
          "sha1": "1d4cf436a3d577df6b486cd9b52691768553bdcf",
          "md5": "026c429eb3c852a22408f9503dc7d73b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.wang.avi",
          "module": "library",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "libViews-1.0.2-SNAPSHOT.aar",
          "url": "libViews-1.0.2-SNAPSHOT.aar",
          "size": 523076,
          "sha512": "d3fde4fa930fc64c196e0f9e008fa9c8e1640078cc6501818a291b0d41839a7708b6a82a13e991a0bab84839aaafb9bb7ca7e8441c4e3b9bdd1506550b146dca",
          "sha256": "3ea74852329fe78632ff461c485f3966afa20036eeca69540e9e32158b54b96e",
          "sha1": "1d4cf436a3d577df6b486cd9b52691768553bdcf",
          "md5": "026c429eb3c852a22408f9503dc7d73b"
        }
      ]
    }
  ]
}
