{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.user",
    "module": "libUser",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libUser-1.0.1-SNAPSHOT.aar",
          "url": "libUser-1.0.1-SNAPSHOT.aar",
          "size": 66081,
          "sha512": "a9f88a048faebf7259c772e36bc66a708624cdb61d1833962f902b4bef434f3a0fe7aafc240a4485a22cd78917c4f25339b6a4c6a2401cfbbfdb83604d4475c6",
          "sha256": "0b2355e523b6a3b59dad79cd3e6352cf347b20ca13e44ab3454eff9d0cd92e9a",
          "sha1": "dba1e04bb60e0d03a4f212fe68f40845774114b5",
          "md5": "9be5c6dbf8a28dc8d75fb37291eb3d01"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libUser-1.0.1-SNAPSHOT.aar",
          "url": "libUser-1.0.1-SNAPSHOT.aar",
          "size": 66081,
          "sha512": "a9f88a048faebf7259c772e36bc66a708624cdb61d1833962f902b4bef434f3a0fe7aafc240a4485a22cd78917c4f25339b6a4c6a2401cfbbfdb83604d4475c6",
          "sha256": "0b2355e523b6a3b59dad79cd3e6352cf347b20ca13e44ab3454eff9d0cd92e9a",
          "sha1": "dba1e04bb60e0d03a4f212fe68f40845774114b5",
          "md5": "9be5c6dbf8a28dc8d75fb37291eb3d01"
        }
      ]
    }
  ]
}
