{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.gradle.classplugin",
    "module": "hive-class-guard",
    "version": "2.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.5.jar",
          "url": "hive-class-guard-2.0.5.jar",
          "size": 135589,
          "sha512": "af321499186c17605a4c67776ae8969591c14c932dd372fb6a8ac3f70213cffd553c39550c10f55e533d0023c4d6930f8ce7c9923610f2485f348f462f978121",
          "sha256": "718bea09f1d9cdaa94d982773b40ca13336af8e79462b0f95b8fbce48abbb964",
          "sha1": "6bd7b3a2ba5e06937353e0ea2cd53cf705c8407e",
          "md5": "a37f9d90c9c33b76179b230f0cb61513"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.5.jar",
          "url": "hive-class-guard-2.0.5.jar",
          "size": 135589,
          "sha512": "af321499186c17605a4c67776ae8969591c14c932dd372fb6a8ac3f70213cffd553c39550c10f55e533d0023c4d6930f8ce7c9923610f2485f348f462f978121",
          "sha256": "718bea09f1d9cdaa94d982773b40ca13336af8e79462b0f95b8fbce48abbb964",
          "sha1": "6bd7b3a2ba5e06937353e0ea2cd53cf705c8407e",
          "md5": "a37f9d90c9c33b76179b230f0cb61513"
        }
      ]
    }
  ]
}
