{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.reader",
    "module": "libReader",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libReader-1.0.1-SNAPSHOT.aar",
          "url": "libReader-1.0.1-SNAPSHOT.aar",
          "size": 473722,
          "sha512": "328489aa92f72b73c9018efcec9bdcac35649a5f6632070633686743e3e4fa3a8528c3e364a7fb8ecb73ded86edab1b07f02f272b33c8c3338d5e741f1568ff6",
          "sha256": "97a962a1fad8cae3968ed897778bff5441b3372c6651c9a726d93a8e16925e01",
          "sha1": "aae3703114d2d9f8f0a3b93c799e2c314b3344c3",
          "md5": "8964dada19799345d5be783cd548a40b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.adv",
          "module": "libAdv",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "cn.wanghaomiao",
          "module": "JsoupXpath",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.github.gedoor",
          "module": "rhino-android",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "net.ricecode",
          "module": "string-similarity",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libReader-1.0.1-SNAPSHOT.aar",
          "url": "libReader-1.0.1-SNAPSHOT.aar",
          "size": 473722,
          "sha512": "328489aa92f72b73c9018efcec9bdcac35649a5f6632070633686743e3e4fa3a8528c3e364a7fb8ecb73ded86edab1b07f02f272b33c8c3338d5e741f1568ff6",
          "sha256": "97a962a1fad8cae3968ed897778bff5441b3372c6651c9a726d93a8e16925e01",
          "sha1": "aae3703114d2d9f8f0a3b93c799e2c314b3344c3",
          "md5": "8964dada19799345d5be783cd548a40b"
        }
      ]
    }
  ]
}
