{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.utils",
    "module": "libUtils",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-no-op",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow-core",
          "version": {
            "requires": "4.2.4"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow",
          "version": {
            "requires": "4.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "libUtils-1.0.6-SNAPSHOT.aar",
          "url": "libUtils-1.0.6-SNAPSHOT.aar",
          "size": 373616,
          "sha512": "5ff5d078b552959e25807cbfb7842cc4944246ca275ecfd623ab8eee0944903a674eb7534fb7d540d22e0a50ec629114a6bec83f43b73ec9c2d474cca17d1553",
          "sha256": "2a505979a634894d7881cd5ecff09c86cdd3f564bf1fc4debcc3e7ac165254db",
          "sha1": "fadd55b3667b3563e935e78712b92506e48dc6c7",
          "md5": "8bdd5143a882e3d9c4ebef1e86c8b726"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-no-op",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow-core",
          "version": {
            "requires": "4.2.4"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow",
          "version": {
            "requires": "4.2.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "libUtils-1.0.6-SNAPSHOT.aar",
          "url": "libUtils-1.0.6-SNAPSHOT.aar",
          "size": 373616,
          "sha512": "5ff5d078b552959e25807cbfb7842cc4944246ca275ecfd623ab8eee0944903a674eb7534fb7d540d22e0a50ec629114a6bec83f43b73ec9c2d474cca17d1553",
          "sha256": "2a505979a634894d7881cd5ecff09c86cdd3f564bf1fc4debcc3e7ac165254db",
          "sha1": "fadd55b3667b3563e935e78712b92506e48dc6c7",
          "md5": "8bdd5143a882e3d9c4ebef1e86c8b726"
        }
      ]
    }
  ]
}
