{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.danmu",
    "module": "libDanmu",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libDanmu-2.0.0-SNAPSHOT.aar",
          "url": "libDanmu-2.0.0-SNAPSHOT.aar",
          "size": 47645,
          "sha512": "513bf86c87c295736663f8b38f155713a5c94bb5ef7abbef82db6464c6b251cfcf9256a4ec7136845e6571d8a4282570c8171aefc7d62327fd9d6e234c944daf",
          "sha256": "76ce88b8e02d44841df49b33c2dd7013876ca08e5e7d60653e9b5feebc11c8d8",
          "sha1": "095519068fd19cc092b865da6d4b66d1506e8d35",
          "md5": "9088070c3ee5851aab380802d09794c6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libDanmu-2.0.0-SNAPSHOT.aar",
          "url": "libDanmu-2.0.0-SNAPSHOT.aar",
          "size": 47645,
          "sha512": "513bf86c87c295736663f8b38f155713a5c94bb5ef7abbef82db6464c6b251cfcf9256a4ec7136845e6571d8a4282570c8171aefc7d62327fd9d6e234c944daf",
          "sha256": "76ce88b8e02d44841df49b33c2dd7013876ca08e5e7d60653e9b5feebc11c8d8",
          "sha1": "095519068fd19cc092b865da6d4b66d1506e8d35",
          "md5": "9088070c3ee5851aab380802d09794c6"
        }
      ]
    }
  ]
}
