{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.rphost",
    "module": "libRPHost",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libRPHost-1.0.1-SNAPSHOT.aar",
          "url": "libRPHost-1.0.1-SNAPSHOT.aar",
          "size": 48077,
          "sha512": "e708982d3080975cb2a15b0c320d9a9c3c5fc7f3db9ad3c00add41fe31c2556382a18f15411dfdd6faa8b86cd97150c4afd7ef5bfbb8d29e6f59d58565dd9a6d",
          "sha256": "5261d1c7023657924b3f3f02b06fb191a2804f95f206adf843f400841ed6e506",
          "sha1": "48a5fc2a9334a383b26965cfb05df9c6877a79c0",
          "md5": "57819a1344fa3ed92520e2327f6208ab"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.qihoo360.replugin",
          "module": "replugin-host-lib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.image",
          "module": "libImage",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.basenative",
          "module": "libBaseNative",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.adv",
          "module": "libAdv",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libRPHost-1.0.1-SNAPSHOT.aar",
          "url": "libRPHost-1.0.1-SNAPSHOT.aar",
          "size": 48077,
          "sha512": "e708982d3080975cb2a15b0c320d9a9c3c5fc7f3db9ad3c00add41fe31c2556382a18f15411dfdd6faa8b86cd97150c4afd7ef5bfbb8d29e6f59d58565dd9a6d",
          "sha256": "5261d1c7023657924b3f3f02b06fb191a2804f95f206adf843f400841ed6e506",
          "sha1": "48a5fc2a9334a383b26965cfb05df9c6877a79c0",
          "md5": "57819a1344fa3ed92520e2327f6208ab"
        }
      ]
    }
  ]
}
