{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.rphost",
    "module": "libRPHost",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libRPHost-1.0.1-SNAPSHOT.aar",
          "url": "libRPHost-1.0.1-SNAPSHOT.aar",
          "size": 43371,
          "sha512": "dda7b423d9389fbbd9635551e3a7682f3b2b5fc50c0c011c296ac17f98f46cd78726181f3c899c059fab234a1374c68b2c26d5decc5bf1c4b582d8c3f989b76b",
          "sha256": "b6f28dc347067cb49ee6714173b95603b93fe59548cfd933797eba966b21ccc1",
          "sha1": "f516aebf868721c64ada758bdcddc88fe4d7991e",
          "md5": "49f477f42a21ab4411ab10eb1a4df6b5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.qihoo360.replugin",
          "module": "replugin-host-lib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libRPHost-1.0.1-SNAPSHOT.aar",
          "url": "libRPHost-1.0.1-SNAPSHOT.aar",
          "size": 43371,
          "sha512": "dda7b423d9389fbbd9635551e3a7682f3b2b5fc50c0c011c296ac17f98f46cd78726181f3c899c059fab234a1374c68b2c26d5decc5bf1c4b582d8c3f989b76b",
          "sha256": "b6f28dc347067cb49ee6714173b95603b93fe59548cfd933797eba966b21ccc1",
          "sha1": "f516aebf868721c64ada758bdcddc88fe4d7991e",
          "md5": "49f477f42a21ab4411ab10eb1a4df6b5"
        }
      ]
    }
  ]
}
