{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.basenative",
    "module": "libBaseNative",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libBaseNative-1.0.2-SNAPSHOT.aar",
          "url": "libBaseNative-1.0.2-SNAPSHOT.aar",
          "size": 64520,
          "sha512": "8205385d018a804d5e0a75e4559daf23e720b27aef4bbefb84b56f5d4b0680f99d8eb56fed6e7d054773b099183ded2863ba7494cc7fd8ffb962df4dcc31f461",
          "sha256": "6bfdd579aaf4604f233450ffece1081fa2ca451fd2e9fb34a9aa67a03567225d",
          "sha1": "5c7963bb5362eb43fe5210378ca8fcfaf38758d2",
          "md5": "ce86754b2c89e3799d2d4043c5eeaf58"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseNative-1.0.2-SNAPSHOT.aar",
          "url": "libBaseNative-1.0.2-SNAPSHOT.aar",
          "size": 64520,
          "sha512": "8205385d018a804d5e0a75e4559daf23e720b27aef4bbefb84b56f5d4b0680f99d8eb56fed6e7d054773b099183ded2863ba7494cc7fd8ffb962df4dcc31f461",
          "sha256": "6bfdd579aaf4604f233450ffece1081fa2ca451fd2e9fb34a9aa67a03567225d",
          "sha1": "5c7963bb5362eb43fe5210378ca8fcfaf38758d2",
          "md5": "ce86754b2c89e3799d2d4043c5eeaf58"
        }
      ]
    }
  ]
}
