{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.push",
    "module": "libPush",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libPush-2.0.0-SNAPSHOT.aar",
          "url": "libPush-2.0.0-SNAPSHOT.aar",
          "size": 32173,
          "sha512": "6166947f831732cd80b5e1cec3268bf7a4aeb42d3369b14007c632fb0d4fb7231e9a6d01cbeabd41580e8fcad92a71e5e7386f23369eafcb63320ddf8058bd51",
          "sha256": "b96977068d069b4b92295591ac0d64fe610a66b7f69c990fa1eebbb39e242add",
          "sha1": "aeff8038d686e6a4ca29c784f248928e6852f5e0",
          "md5": "e09a9888509ac959fc738948ad551e48"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "21.0.0"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "alicloud-httpdns",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "alicloud-utils",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "alicloud_beacon",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo-accs",
          "version": {
            "requires": "3.3.9.7-open"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo_networksdk",
          "version": {
            "requires": "3.5.5"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo_tlog",
          "version": {
            "requires": "3.0.0.17"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "agoo_tnet4android",
          "version": {
            "requires": "3.1.14.9"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libPush-2.0.0-SNAPSHOT.aar",
          "url": "libPush-2.0.0-SNAPSHOT.aar",
          "size": 32173,
          "sha512": "6166947f831732cd80b5e1cec3268bf7a4aeb42d3369b14007c632fb0d4fb7231e9a6d01cbeabd41580e8fcad92a71e5e7386f23369eafcb63320ddf8058bd51",
          "sha256": "b96977068d069b4b92295591ac0d64fe610a66b7f69c990fa1eebbb39e242add",
          "sha1": "aeff8038d686e6a4ca29c784f248928e6852f5e0",
          "md5": "e09a9888509ac959fc738948ad551e48"
        }
      ]
    }
  ]
}
