{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.thunder",
    "module": "libThunder",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libThunder-2.0.0-SNAPSHOT.aar",
          "url": "libThunder-2.0.0-SNAPSHOT.aar",
          "size": 2835903,
          "sha512": "a301e92b96eca94ca0ce01c8c52a4afeb61c20793a7fd00d7ea203ea58e6225674b9e9962361afc596956a4355f7952cfbe154a1a3344745402b6a92ceaf3d70",
          "sha256": "a9b69f74b1e5c3ee6894dae95ae304a577b083b10a33b6eab0cbd2763ca4389e",
          "sha1": "419dc25f0e1da19ae0bc1d40715eeb93c6cd2c92",
          "md5": "4a894e86417be0654f4851c367e20f77"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libThunder-2.0.0-SNAPSHOT.aar",
          "url": "libThunder-2.0.0-SNAPSHOT.aar",
          "size": 2835903,
          "sha512": "a301e92b96eca94ca0ce01c8c52a4afeb61c20793a7fd00d7ea203ea58e6225674b9e9962361afc596956a4355f7952cfbe154a1a3344745402b6a92ceaf3d70",
          "sha256": "a9b69f74b1e5c3ee6894dae95ae304a577b083b10a33b6eab0cbd2763ca4389e",
          "sha1": "419dc25f0e1da19ae0bc1d40715eeb93c6cd2c92",
          "md5": "4a894e86417be0654f4851c367e20f77"
        }
      ]
    }
  ]
}
