{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.downloader",
    "module": "libDownloader",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libDownloader-1.0.1-SNAPSHOT.aar",
          "url": "libDownloader-1.0.1-SNAPSHOT.aar",
          "size": 110286,
          "sha512": "0e3ea611d5bf95788dac71ff7e097095ff3ab9e2be8c3fce8cfb9e02d3e496cc46faf19459e8758eb44d981137a2eb81d513b3f70c86d32ddaa3ec5006c05cdc",
          "sha256": "f933072fc78ec27d7ca9d84b7a6f30667378efd19819b900254350591876c0af",
          "sha1": "cd2c0c24d3eb2bd820d1649bf9188d365e6745a7",
          "md5": "2e642573582bd5f9cc299d988f34c0f5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.koushikdutta.async",
          "module": "androidasync",
          "version": {
            "requires": "2.+"
          }
        },
        {
          "group": "com.arialyy.aria",
          "module": "core",
          "version": {
            "requires": "3.8.15"
          }
        },
        {
          "group": "com.arialyy.aria",
          "module": "ftpComponent",
          "version": {
            "requires": "3.8.15"
          }
        },
        {
          "group": "com.arialyy.aria",
          "module": "sftpComponent",
          "version": {
            "requires": "3.8.15"
          }
        },
        {
          "group": "com.arialyy.aria",
          "module": "m3u8Component",
          "version": {
            "requires": "3.8.15"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libDownloader-1.0.1-SNAPSHOT.aar",
          "url": "libDownloader-1.0.1-SNAPSHOT.aar",
          "size": 110286,
          "sha512": "0e3ea611d5bf95788dac71ff7e097095ff3ab9e2be8c3fce8cfb9e02d3e496cc46faf19459e8758eb44d981137a2eb81d513b3f70c86d32ddaa3ec5006c05cdc",
          "sha256": "f933072fc78ec27d7ca9d84b7a6f30667378efd19819b900254350591876c0af",
          "sha1": "cd2c0c24d3eb2bd820d1649bf9188d365e6745a7",
          "md5": "2e642573582bd5f9cc299d988f34c0f5"
        }
      ]
    }
  ]
}
