{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.downloader",
    "module": "libDownloader",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libDownloader-1.0.1-SNAPSHOT.aar",
          "url": "libDownloader-1.0.1-SNAPSHOT.aar",
          "size": 110281,
          "sha512": "77222f8c6a502ec06d7724d78e196a6bd41a257611feebdb449b983085aef476505770a648f23c2c5f0e5cc17d819cede1517f4a3ecb13defd93e7ec7a9b1f46",
          "sha256": "0ebe4689e733be64336f3e34edeebcd3837d017ce07d0e8a5d87238d8b355cb8",
          "sha1": "8ab887a13234c57858c1b274f29d568940e93be0",
          "md5": "1abfeff4eb8bad468985a7c288214e25"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.koushikdutta.async",
          "module": "androidasync",
          "version": {
            "requires": "2.+"
          }
        },
        {
          "group": "com.arialyy.aria",
          "module": "core",
          "version": {
            "requires": "3.8.15"
          }
        },
        {
          "group": "com.arialyy.aria",
          "module": "ftpComponent",
          "version": {
            "requires": "3.8.15"
          }
        },
        {
          "group": "com.arialyy.aria",
          "module": "sftpComponent",
          "version": {
            "requires": "3.8.15"
          }
        },
        {
          "group": "com.arialyy.aria",
          "module": "m3u8Component",
          "version": {
            "requires": "3.8.15"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libDownloader-1.0.1-SNAPSHOT.aar",
          "url": "libDownloader-1.0.1-SNAPSHOT.aar",
          "size": 110281,
          "sha512": "77222f8c6a502ec06d7724d78e196a6bd41a257611feebdb449b983085aef476505770a648f23c2c5f0e5cc17d819cede1517f4a3ecb13defd93e7ec7a9b1f46",
          "sha256": "0ebe4689e733be64336f3e34edeebcd3837d017ce07d0e8a5d87238d8b355cb8",
          "sha1": "8ab887a13234c57858c1b274f29d568940e93be0",
          "md5": "1abfeff4eb8bad468985a7c288214e25"
        }
      ]
    }
  ]
}
