{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.audio",
    "module": "libAudio",
    "version": "2.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libAudio-2.0.1-SNAPSHOT.aar",
          "url": "libAudio-2.0.1-SNAPSHOT.aar",
          "size": 111381,
          "sha512": "dff3ede41e297a999132b8c4b602098482d5bac3fd7cfc4588445013312f1b21aeb52d8baaf32521404e70649c27ba04e075ae950e331b812ab092a0ebb53481",
          "sha256": "557413c52c3b19da3702a60a90949420281b705a9bb9c9e8a0f155c7ed3eb18d",
          "sha1": "483e3f6556654de7c934668efc1f6fe6bd925c0d",
          "md5": "0c951855442485539cf3d8b2416646e3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.microsoft.cognitiveservices.speech",
          "module": "client-sdk",
          "version": {
            "requires": "1.28.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.25"
          }
        }
      ],
      "files": [
        {
          "name": "libAudio-2.0.1-SNAPSHOT.aar",
          "url": "libAudio-2.0.1-SNAPSHOT.aar",
          "size": 111381,
          "sha512": "dff3ede41e297a999132b8c4b602098482d5bac3fd7cfc4588445013312f1b21aeb52d8baaf32521404e70649c27ba04e075ae950e331b812ab092a0ebb53481",
          "sha256": "557413c52c3b19da3702a60a90949420281b705a9bb9c9e8a0f155c7ed3eb18d",
          "sha1": "483e3f6556654de7c934668efc1f6fe6bd925c0d",
          "md5": "0c951855442485539cf3d8b2416646e3"
        }
      ]
    }
  ]
}
