{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.draw",
    "module": "libDraw",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libDraw-1.0.1-SNAPSHOT.aar",
          "url": "libDraw-1.0.1-SNAPSHOT.aar",
          "size": 67188,
          "sha512": "5ae26d7288fbd06ab89d56c4b322a43d20ca5c1c8bd6510157e3577bbb55e9c1879b5399c2c0fff251f59f1656a59cf2ec5c28005cd91cb8c6859140d383204d",
          "sha256": "a77a0bbc9df1f70f31dd73f94079c3a4b0abaafac8b08d87beae232c98b78fa9",
          "sha1": "28d04e981828884f66f621aa81f003d4d3c5981b",
          "md5": "0331069256c4d292d04790cb78d99ccb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libDraw-1.0.1-SNAPSHOT.aar",
          "url": "libDraw-1.0.1-SNAPSHOT.aar",
          "size": 67188,
          "sha512": "5ae26d7288fbd06ab89d56c4b322a43d20ca5c1c8bd6510157e3577bbb55e9c1879b5399c2c0fff251f59f1656a59cf2ec5c28005cd91cb8c6859140d383204d",
          "sha256": "a77a0bbc9df1f70f31dd73f94079c3a4b0abaafac8b08d87beae232c98b78fa9",
          "sha1": "28d04e981828884f66f621aa81f003d4d3c5981b",
          "md5": "0331069256c4d292d04790cb78d99ccb"
        }
      ]
    }
  ]
}
