{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.views",
    "module": "libViews",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libViews-1.0.3-SNAPSHOT.aar",
          "url": "libViews-1.0.3-SNAPSHOT.aar",
          "size": 570184,
          "sha512": "142be1785feb00a351f20ed9cee0ff3401b76e2875635b593a8ab17692ccd89857eb3fe14fa08ed21951314f0642868a5dc831a26f17f42f1f6517306316cea8",
          "sha256": "6ccd841b99f01d84f67cbfa4c4eb14e836dc12715fd2d26b36f9924d35623bd7",
          "sha1": "d940ce0fdde18bf81906bf1ef1090a546575e934",
          "md5": "2f3ae0bbde1568d5fd938df911fe6de5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.wang.avi",
          "module": "library",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "libViews-1.0.3-SNAPSHOT.aar",
          "url": "libViews-1.0.3-SNAPSHOT.aar",
          "size": 570184,
          "sha512": "142be1785feb00a351f20ed9cee0ff3401b76e2875635b593a8ab17692ccd89857eb3fe14fa08ed21951314f0642868a5dc831a26f17f42f1f6517306316cea8",
          "sha256": "6ccd841b99f01d84f67cbfa4c4eb14e836dc12715fd2d26b36f9924d35623bd7",
          "sha1": "d940ce0fdde18bf81906bf1ef1090a546575e934",
          "md5": "2f3ae0bbde1568d5fd938df911fe6de5"
        }
      ]
    }
  ]
}
