{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.clear",
    "module": "libClear",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libClear-2.0.0-SNAPSHOT.aar",
          "url": "libClear-2.0.0-SNAPSHOT.aar",
          "size": 34879,
          "sha512": "2100e9c26bf043dcccba2a510ae16ecf8311e2a9616da310e9b8382d6e9346d0a0e4d0a295214e6ac0e660733266e8d1e4ce5d0afdf4cb3ae45259ffb0b6d4e8",
          "sha256": "0bcf78ef452760133bd90c929b87fd774f2ffa60a18e68572c9240226d46bf79",
          "sha1": "5d8998a061511f3cca21614d6d964e1257d8cacd",
          "md5": "6a018a6465105ea365588dc6e5229c82"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libClear-2.0.0-SNAPSHOT.aar",
          "url": "libClear-2.0.0-SNAPSHOT.aar",
          "size": 34879,
          "sha512": "2100e9c26bf043dcccba2a510ae16ecf8311e2a9616da310e9b8382d6e9346d0a0e4d0a295214e6ac0e660733266e8d1e4ce5d0afdf4cb3ae45259ffb0b6d4e8",
          "sha256": "0bcf78ef452760133bd90c929b87fd774f2ffa60a18e68572c9240226d46bf79",
          "sha1": "5d8998a061511f3cca21614d6d964e1257d8cacd",
          "md5": "6a018a6465105ea365588dc6e5229c82"
        }
      ]
    }
  ]
}
