{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.cache",
    "module": "libCache",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCache-1.0.1-SNAPSHOT.aar",
          "url": "libCache-1.0.1-SNAPSHOT.aar",
          "size": 110109,
          "sha512": "da8b60ab5b93df46b535ea1caa589d451997d7c1a3d7034f126574cb3dc0a388b9d063fc3f2ff6ee76d44803ec65d157809940c947df85e8a5f61559daef0abb",
          "sha256": "d94f011b5b3847f3fa2c9bf6dae70fbbf1b939634d78950ce91d9bff032632c2",
          "sha1": "65190e8ef3054e874bec8841be717c73f8a84754",
          "md5": "b604c67e2d3a719c1566e9ac17331b4e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libCache-1.0.1-SNAPSHOT.aar",
          "url": "libCache-1.0.1-SNAPSHOT.aar",
          "size": 110109,
          "sha512": "da8b60ab5b93df46b535ea1caa589d451997d7c1a3d7034f126574cb3dc0a388b9d063fc3f2ff6ee76d44803ec65d157809940c947df85e8a5f61559daef0abb",
          "sha256": "d94f011b5b3847f3fa2c9bf6dae70fbbf1b939634d78950ce91d9bff032632c2",
          "sha1": "65190e8ef3054e874bec8841be717c73f8a84754",
          "md5": "b604c67e2d3a719c1566e9ac17331b4e"
        }
      ]
    }
  ]
}
