{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.btcore",
    "module": "libBtCore",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libBtCore-1.0.1-SNAPSHOT.aar",
          "url": "libBtCore-1.0.1-SNAPSHOT.aar",
          "size": 2305230,
          "sha512": "5bea55ff98763d122416a71998c28fcf5dbfb11896874bc12a41dd8a5162f0a42608ca0998ff05d8dd730f438310bc92b7f81d88266512174cd76b9b6bcf4f25",
          "sha256": "21af5d5d3ad4f80bbfd71d91a6400ba16d3916e35913263427c9cba5befb5cd7",
          "sha1": "70d87f553adaaaa6ddb30406b1cbed6cd9f93ae3",
          "md5": "e1606d8eb0a5e6613f68eb96470283b3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libBtCore-1.0.1-SNAPSHOT.aar",
          "url": "libBtCore-1.0.1-SNAPSHOT.aar",
          "size": 2305230,
          "sha512": "5bea55ff98763d122416a71998c28fcf5dbfb11896874bc12a41dd8a5162f0a42608ca0998ff05d8dd730f438310bc92b7f81d88266512174cd76b9b6bcf4f25",
          "sha256": "21af5d5d3ad4f80bbfd71d91a6400ba16d3916e35913263427c9cba5befb5cd7",
          "sha1": "70d87f553adaaaa6ddb30406b1cbed6cd9f93ae3",
          "md5": "e1606d8eb0a5e6613f68eb96470283b3"
        }
      ]
    }
  ]
}
