{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.third",
    "module": "libThird",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libThird-2.0.0-SNAPSHOT.aar",
          "url": "libThird-2.0.0-SNAPSHOT.aar",
          "size": 745890,
          "sha512": "7d4c9af2487dfe4b72806471bd009aad078969389ecc3bc3e66bd4ea00566f2540f48f3c2a3ee7435495532bfe365ebb67ac5bd2a813e4160cec94e828be23d0",
          "sha256": "fc7dbcb634306b24f3dc8d6b7abcf0b44c128792c71d5c773908cb6ac99ff063",
          "sha1": "403f61478d3e0a47498d7fc1f64ad6e09061129b",
          "md5": "7ef6ada12418df4af6f12dfc93662872"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libThird-2.0.0-SNAPSHOT.aar",
          "url": "libThird-2.0.0-SNAPSHOT.aar",
          "size": 745890,
          "sha512": "7d4c9af2487dfe4b72806471bd009aad078969389ecc3bc3e66bd4ea00566f2540f48f3c2a3ee7435495532bfe365ebb67ac5bd2a813e4160cec94e828be23d0",
          "sha256": "fc7dbcb634306b24f3dc8d6b7abcf0b44c128792c71d5c773908cb6ac99ff063",
          "sha1": "403f61478d3e0a47498d7fc1f64ad6e09061129b",
          "md5": "7ef6ada12418df4af6f12dfc93662872"
        }
      ]
    }
  ]
}
