{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.cast",
    "module": "libCast",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCast-1.0.1-SNAPSHOT.aar",
          "url": "libCast-1.0.1-SNAPSHOT.aar",
          "size": 148300,
          "sha512": "2c6a2a400ee6fcf9c63a3cd1f5040e59097faa6671274718a7b6e1eee70997aed96b22af0552b8853abff5ef1858065a7a671d49908aa47594966de57ecd71b6",
          "sha256": "ecd2ebe7f0d34dcb69a2d89e18523075cc5c403649d0528ed07c7ff61862a67e",
          "sha1": "eab489623e4557b795be90b4ccf9285ce2ef698b",
          "md5": "aca061a1d7faf7e09dba2988f292fd59"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.wang.avi",
          "module": "library",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.fourthline.cling",
          "module": "cling-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.fourthline.cling",
          "module": "cling-support",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-server",
          "version": {
            "requires": "8.1.12.v20130726"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-servlet",
          "version": {
            "requires": "8.1.12.v20130726"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-client",
          "version": {
            "requires": "8.1.12.v20130726"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libCast-1.0.1-SNAPSHOT.aar",
          "url": "libCast-1.0.1-SNAPSHOT.aar",
          "size": 148300,
          "sha512": "2c6a2a400ee6fcf9c63a3cd1f5040e59097faa6671274718a7b6e1eee70997aed96b22af0552b8853abff5ef1858065a7a671d49908aa47594966de57ecd71b6",
          "sha256": "ecd2ebe7f0d34dcb69a2d89e18523075cc5c403649d0528ed07c7ff61862a67e",
          "sha1": "eab489623e4557b795be90b4ccf9285ce2ef698b",
          "md5": "aca061a1d7faf7e09dba2988f292fd59"
        }
      ]
    }
  ]
}
