{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.cast",
    "module": "libCast",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCast-1.0.1-SNAPSHOT.aar",
          "url": "libCast-1.0.1-SNAPSHOT.aar",
          "size": 150355,
          "sha512": "51a91cf3de037bf8f1394b07c600c3c98204ca6269b84569d6966b58e9fb0958ca4fc89602e07266c4121399e4041f815988cef91fd737440e09c67ae8e6465f",
          "sha256": "7f25ca584aed6799b33b8cfb4ee974071a0a84a0b3455769ebf51f476ccdb5cd",
          "sha1": "68e1f3494f36c607cfe7a9bf5944fae883eb9928",
          "md5": "853aee6b02ee676d464d3e0049708115"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.wang.avi",
          "module": "library",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.fourthline.cling",
          "module": "cling-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.fourthline.cling",
          "module": "cling-support",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-server",
          "version": {
            "requires": "8.1.12.v20130726"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-servlet",
          "version": {
            "requires": "8.1.12.v20130726"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-client",
          "version": {
            "requires": "8.1.12.v20130726"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libCast-1.0.1-SNAPSHOT.aar",
          "url": "libCast-1.0.1-SNAPSHOT.aar",
          "size": 150355,
          "sha512": "51a91cf3de037bf8f1394b07c600c3c98204ca6269b84569d6966b58e9fb0958ca4fc89602e07266c4121399e4041f815988cef91fd737440e09c67ae8e6465f",
          "sha256": "7f25ca584aed6799b33b8cfb4ee974071a0a84a0b3455769ebf51f476ccdb5cd",
          "sha1": "68e1f3494f36c607cfe7a9bf5944fae883eb9928",
          "md5": "853aee6b02ee676d464d3e0049708115"
        }
      ]
    }
  ]
}
