{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.compon",
    "module": "libCompon",
    "version": "1.0.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCompon-1.0.10-SNAPSHOT.aar",
          "url": "libCompon-1.0.10-SNAPSHOT.aar",
          "size": 46708,
          "sha512": "f7a2d34b203e23c3920226e0dfc835c9a27afcaf558b6e5df52b23d59fee050ab152686fede63b226364320e9e3184957aa88081e47131b24c1f6e715bd18542",
          "sha256": "5c0500d1eb97b3b4ee9383d93e0f89f2b9a79bda03e4f9c510564f8c2a8fd8e3",
          "sha1": "75fa3bdc10242b7cab836cefa762d79da787fd59",
          "md5": "54666da74e547d852c6e33c4b3e9d4ad"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjrt",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libCompon-1.0.10-SNAPSHOT.aar",
          "url": "libCompon-1.0.10-SNAPSHOT.aar",
          "size": 46708,
          "sha512": "f7a2d34b203e23c3920226e0dfc835c9a27afcaf558b6e5df52b23d59fee050ab152686fede63b226364320e9e3184957aa88081e47131b24c1f6e715bd18542",
          "sha256": "5c0500d1eb97b3b4ee9383d93e0f89f2b9a79bda03e4f9c510564f8c2a8fd8e3",
          "sha1": "75fa3bdc10242b7cab836cefa762d79da787fd59",
          "md5": "54666da74e547d852c6e33c4b3e9d4ad"
        }
      ]
    }
  ]
}
