{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.compon",
    "module": "libCompon",
    "version": "1.0.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCompon-1.0.10-SNAPSHOT.aar",
          "url": "libCompon-1.0.10-SNAPSHOT.aar",
          "size": 46778,
          "sha512": "c086812ea6f951a5ecc041934098d78ee5ca94f55ad60fab8ff10f392c89543618b89ccaa85756ba4dd4af0edb20828d78df15928c7db40f740d0ab27aa067ff",
          "sha256": "3d04495d5b8f89a2c721c968a4084866001e9cf1dd9283cef7843be8015d881d",
          "sha1": "36bd11dfe3c3998061df380df310037df4ed8b18",
          "md5": "3a748cb61e8ac0f7cbd3963fc8db36b7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjrt",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libCompon-1.0.10-SNAPSHOT.aar",
          "url": "libCompon-1.0.10-SNAPSHOT.aar",
          "size": 46778,
          "sha512": "c086812ea6f951a5ecc041934098d78ee5ca94f55ad60fab8ff10f392c89543618b89ccaa85756ba4dd4af0edb20828d78df15928c7db40f740d0ab27aa067ff",
          "sha256": "3d04495d5b8f89a2c721c968a4084866001e9cf1dd9283cef7843be8015d881d",
          "sha1": "36bd11dfe3c3998061df380df310037df4ed8b18",
          "md5": "3a748cb61e8ac0f7cbd3963fc8db36b7"
        }
      ]
    }
  ]
}
