{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.draw",
    "module": "libDraw",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libDraw-2.0.0-SNAPSHOT.aar",
          "url": "libDraw-2.0.0-SNAPSHOT.aar",
          "size": 67552,
          "sha512": "35637f6f9ccda5561e9f0edf924f2ebb5766752f2a1c9e45cc55b9afaaaed40eaaecb9e094bba0f31245d7860bc4ff0cd9e22074ca84041bb31715541c9b749f",
          "sha256": "3c064c753651ca32324d2861e8479b95c76cbf6dc160148fd3ebe43ea81c5b10",
          "sha1": "ebdb7fd2d5a940d95fa7a3e0fdfc5d9f47ee9e0e",
          "md5": "55e1995ab52553b9537ecf6cfda63f86"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libDraw-2.0.0-SNAPSHOT.aar",
          "url": "libDraw-2.0.0-SNAPSHOT.aar",
          "size": 67552,
          "sha512": "35637f6f9ccda5561e9f0edf924f2ebb5766752f2a1c9e45cc55b9afaaaed40eaaecb9e094bba0f31245d7860bc4ff0cd9e22074ca84041bb31715541c9b749f",
          "sha256": "3c064c753651ca32324d2861e8479b95c76cbf6dc160148fd3ebe43ea81c5b10",
          "sha1": "ebdb7fd2d5a940d95fa7a3e0fdfc5d9f47ee9e0e",
          "md5": "55e1995ab52553b9537ecf6cfda63f86"
        }
      ]
    }
  ]
}
