{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.third",
    "module": "libThird",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libThird-1.0.1-SNAPSHOT.aar",
          "url": "libThird-1.0.1-SNAPSHOT.aar",
          "size": 743929,
          "sha512": "d0b3c3eebc4bd75aa6e8e222af2657f6f03b058d63a52fc20f1f5a511885a1514e43d5325077d2f83770872923762b81488b41461aacf50524b03197bf3c12b8",
          "sha256": "fee97abc0a1b4809d3e92819eb1a47bf173ce2b99c5ee007e744c4b684606065",
          "sha1": "caf2bec89457aaea5b2cf31f165086dc728036f4",
          "md5": "097d10518b37bc325936e9c4514b1fed"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libThird-1.0.1-SNAPSHOT.aar",
          "url": "libThird-1.0.1-SNAPSHOT.aar",
          "size": 743929,
          "sha512": "d0b3c3eebc4bd75aa6e8e222af2657f6f03b058d63a52fc20f1f5a511885a1514e43d5325077d2f83770872923762b81488b41461aacf50524b03197bf3c12b8",
          "sha256": "fee97abc0a1b4809d3e92819eb1a47bf173ce2b99c5ee007e744c4b684606065",
          "sha1": "caf2bec89457aaea5b2cf31f165086dc728036f4",
          "md5": "097d10518b37bc325936e9c4514b1fed"
        }
      ]
    }
  ]
}
