{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.third",
    "module": "libThird",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libThird-1.0.1-SNAPSHOT.aar",
          "url": "libThird-1.0.1-SNAPSHOT.aar",
          "size": 745865,
          "sha512": "b50fb59450738d9ca8220bab07c3f1e7dc127fc47bdc09029df7f2502740b8275142236b2380d6a503a557a0e0068ec07f82fabb0dc14e119d21ccddb2d57639",
          "sha256": "abd7ab36b61945adc2f6d4f408f710b70b87ccf28d3dee2c1934d5dd596d3779",
          "sha1": "dc0aa6ff5c4509fa87977e5903562256a6642bc7",
          "md5": "c46bad7ab5d7431ebb2b8ecb2825ab75"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.3-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libThird-1.0.1-SNAPSHOT.aar",
          "url": "libThird-1.0.1-SNAPSHOT.aar",
          "size": 745865,
          "sha512": "b50fb59450738d9ca8220bab07c3f1e7dc127fc47bdc09029df7f2502740b8275142236b2380d6a503a557a0e0068ec07f82fabb0dc14e119d21ccddb2d57639",
          "sha256": "abd7ab36b61945adc2f6d4f408f710b70b87ccf28d3dee2c1934d5dd596d3779",
          "sha1": "dc0aa6ff5c4509fa87977e5903562256a6642bc7",
          "md5": "c46bad7ab5d7431ebb2b8ecb2825ab75"
        }
      ]
    }
  ]
}
