{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.thunder",
    "module": "libThunder",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libThunder-1.0.1-SNAPSHOT.aar",
          "url": "libThunder-1.0.1-SNAPSHOT.aar",
          "size": 2834081,
          "sha512": "95a2b4524092318a3ee547cab6c303bc888e8011945ef0633ee6b7de211c605fe24be5239bab418adc127a542bc306e63bb6e50310d360621ebd425bb408f06a",
          "sha256": "b2a74e30e0d576630bfc852689ec9c579b0d93607b964f55fb72e101c9b9b827",
          "sha1": "4130b6060b241e5ecaf06255fad591e8c72fabdd",
          "md5": "c3b17c86944f76ed6bb4dbd150d1e74b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libThunder-1.0.1-SNAPSHOT.aar",
          "url": "libThunder-1.0.1-SNAPSHOT.aar",
          "size": 2834081,
          "sha512": "95a2b4524092318a3ee547cab6c303bc888e8011945ef0633ee6b7de211c605fe24be5239bab418adc127a542bc306e63bb6e50310d360621ebd425bb408f06a",
          "sha256": "b2a74e30e0d576630bfc852689ec9c579b0d93607b964f55fb72e101c9b9b827",
          "sha1": "4130b6060b241e5ecaf06255fad591e8c72fabdd",
          "md5": "c3b17c86944f76ed6bb4dbd150d1e74b"
        }
      ]
    }
  ]
}
