{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.compon",
    "module": "libCompon",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCompon-2.0.0-SNAPSHOT.aar",
          "url": "libCompon-2.0.0-SNAPSHOT.aar",
          "size": 49569,
          "sha512": "697b5e6d22c64f1cf700ac195ea6f1a935293c15c448b2ac466121dc9d86360a88f469be64fe28b68ae50e459c66b1be37e3f9e0729f562789ad5f5f3b91a0b9",
          "sha256": "2643d6a1b1d51dd57661dfbf5b07012833bb9f376212d2139b1897edf74c18bb",
          "sha1": "8c0720ff9a5c475accb8a195a8b62230b51b7241",
          "md5": "3625baac856d6f8ba6ed7ac839877125"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.aspectj",
          "module": "aspectjrt",
          "version": {
            "requires": "1.9.4"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libCompon-2.0.0-SNAPSHOT.aar",
          "url": "libCompon-2.0.0-SNAPSHOT.aar",
          "size": 49569,
          "sha512": "697b5e6d22c64f1cf700ac195ea6f1a935293c15c448b2ac466121dc9d86360a88f469be64fe28b68ae50e459c66b1be37e3f9e0729f562789ad5f5f3b91a0b9",
          "sha256": "2643d6a1b1d51dd57661dfbf5b07012833bb9f376212d2139b1897edf74c18bb",
          "sha1": "8c0720ff9a5c475accb8a195a8b62230b51b7241",
          "md5": "3625baac856d6f8ba6ed7ac839877125"
        }
      ]
    }
  ]
}
