{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.adv",
    "module": "libAdv",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libAdv-2.0.0-SNAPSHOT.aar",
          "url": "libAdv-2.0.0-SNAPSHOT.aar",
          "size": 246879,
          "sha512": "bb23f09907e53434522862fe1c6dc2fc2e9367101c398e1249ce49bd0dc114e6e3a91adda7af77f4f7916dae8383b64cdacb8f7139dc053df2882e87781fcf48",
          "sha256": "0ab7df78b14c2c9b54acc42420143296186094f9b90c31765936dfcae8ea2a85",
          "sha1": "875a8688a2fb770b4b2a68455bd65975cc14b998",
          "md5": "6bdc9b5a005b1e247c4670ecebd46678"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.image",
          "module": "libImage",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.basenative",
          "module": "libBaseNative",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-android-sdk",
          "version": {
            "requires": "6.0.0"
          },
          "excludes": [
            {
              "group": "com.google.zxing",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.facebook.android",
          "module": "audience-network-sdk",
          "version": {
            "requires": "6.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "reward",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "interstitialvideo",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbnative",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbnativeadvanced",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "interstitial",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbbanner",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbsplash",
          "version": {
            "requires": "15.8.01"
          }
        },
        {
          "group": "com.adcolony",
          "module": "sdk",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "libAdv-2.0.0-SNAPSHOT.aar",
          "url": "libAdv-2.0.0-SNAPSHOT.aar",
          "size": 246879,
          "sha512": "bb23f09907e53434522862fe1c6dc2fc2e9367101c398e1249ce49bd0dc114e6e3a91adda7af77f4f7916dae8383b64cdacb8f7139dc053df2882e87781fcf48",
          "sha256": "0ab7df78b14c2c9b54acc42420143296186094f9b90c31765936dfcae8ea2a85",
          "sha1": "875a8688a2fb770b4b2a68455bd65975cc14b998",
          "md5": "6bdc9b5a005b1e247c4670ecebd46678"
        }
      ]
    }
  ]
}
