{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.gradle.classplugin",
    "module": "hive-class-guard",
    "version": "2.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.8.jar",
          "url": "hive-class-guard-2.0.8.jar",
          "size": 135922,
          "sha512": "e19791433bd1ba85af834adc5e85e989f6396508664faa45a486c5af1f007232143d1f4787391648b62a1f3e085a1788b101d0c5ecbb18c741b704e35a977aaa",
          "sha256": "73060575179437260e63ef7e065e8e7155a2bbfb96794b922e0a5193be49709f",
          "sha1": "142dcc26ecca4fa01068b7a3c166e434752c9121",
          "md5": "a2035bcc925321eeb6446451fcaba488"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.8.jar",
          "url": "hive-class-guard-2.0.8.jar",
          "size": 135922,
          "sha512": "e19791433bd1ba85af834adc5e85e989f6396508664faa45a486c5af1f007232143d1f4787391648b62a1f3e085a1788b101d0c5ecbb18c741b704e35a977aaa",
          "sha256": "73060575179437260e63ef7e065e8e7155a2bbfb96794b922e0a5193be49709f",
          "sha1": "142dcc26ecca4fa01068b7a3c166e434752c9121",
          "md5": "a2035bcc925321eeb6446451fcaba488"
        }
      ]
    }
  ]
}
