{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.gradle.classplugin",
    "module": "hive-class-guard",
    "version": "2.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.11.jar",
          "url": "hive-class-guard-2.0.11.jar",
          "size": 139063,
          "sha512": "cb3eb130eb33aa545013f16b7f065586a9c99f4d21ac41a572aac83b2ca881d1058e4a7a963e6b472de173c7bfbbd876e5a7c1c9bf1a0ebf8cb110d5b65ff0cf",
          "sha256": "eb317a664199b4a5b9c4e3fb253b28630c9c07ea482a7f2aa344dc6907523f1b",
          "sha1": "3a2f537f6de5e6f0404a28bd3bb00136d440c734",
          "md5": "486981416d5868f8798f99187a25fd82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.11.jar",
          "url": "hive-class-guard-2.0.11.jar",
          "size": 139063,
          "sha512": "cb3eb130eb33aa545013f16b7f065586a9c99f4d21ac41a572aac83b2ca881d1058e4a7a963e6b472de173c7bfbbd876e5a7c1c9bf1a0ebf8cb110d5b65ff0cf",
          "sha256": "eb317a664199b4a5b9c4e3fb253b28630c9c07ea482a7f2aa344dc6907523f1b",
          "sha1": "3a2f537f6de5e6f0404a28bd3bb00136d440c734",
          "md5": "486981416d5868f8798f99187a25fd82"
        }
      ]
    }
  ]
}
