{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.music",
    "module": "libMusic",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libMusic-2.0.0-SNAPSHOT.aar",
          "url": "libMusic-2.0.0-SNAPSHOT.aar",
          "size": 241684,
          "sha512": "faa8fb92f57ce79c03833a8e9d284a589db6cc71136b8a0ce3b1618b356b9a776eaefe12b18ad1f523118ed31b647082778993103d5197518a2751e51bff2fb8",
          "sha256": "eee0b4312c6001212dd22203eeb3ed799ce043c6b7e222a6cb7179e3793896ef",
          "sha1": "4bec94a9065de5b08b6b4c182a94e7056bbdeca4",
          "md5": "f9d0ea8ce52957c6029840b691b783a6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.image",
          "module": "libImage",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.basenative",
          "module": "libBaseNative",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.files",
          "module": "libFiles",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.third",
          "module": "libThird",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libMusic-2.0.0-SNAPSHOT.aar",
          "url": "libMusic-2.0.0-SNAPSHOT.aar",
          "size": 241684,
          "sha512": "faa8fb92f57ce79c03833a8e9d284a589db6cc71136b8a0ce3b1618b356b9a776eaefe12b18ad1f523118ed31b647082778993103d5197518a2751e51bff2fb8",
          "sha256": "eee0b4312c6001212dd22203eeb3ed799ce043c6b7e222a6cb7179e3793896ef",
          "sha1": "4bec94a9065de5b08b6b4c182a94e7056bbdeca4",
          "md5": "f9d0ea8ce52957c6029840b691b783a6"
        }
      ]
    }
  ]
}
