{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.views",
    "module": "libViews",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libViews-2.0.0-SNAPSHOT.aar",
          "url": "libViews-2.0.0-SNAPSHOT.aar",
          "size": 570062,
          "sha512": "12b45848f50b611690384c96fae623b1e3cd24656ee6ca3d71941f232f89acf5b9b4aa8add2ad106664ff49334137ebdbb9b38d64a60b302ff4a87192a1cb87c",
          "sha256": "5bfcacb748e46db4815213a95aad7ff1287a1c70430ea9c4ab949d31cd6d66c9",
          "sha1": "0cb6c538cb0452bf61e43d4d609c1b62f9bf4511",
          "md5": "f2d4e1a50a18746d80de0989a579617e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.wang.avi",
          "module": "library",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "libViews-2.0.0-SNAPSHOT.aar",
          "url": "libViews-2.0.0-SNAPSHOT.aar",
          "size": 570062,
          "sha512": "12b45848f50b611690384c96fae623b1e3cd24656ee6ca3d71941f232f89acf5b9b4aa8add2ad106664ff49334137ebdbb9b38d64a60b302ff4a87192a1cb87c",
          "sha256": "5bfcacb748e46db4815213a95aad7ff1287a1c70430ea9c4ab949d31cd6d66c9",
          "sha1": "0cb6c538cb0452bf61e43d4d609c1b62f9bf4511",
          "md5": "f2d4e1a50a18746d80de0989a579617e"
        }
      ]
    }
  ]
}
