{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.downloader",
    "module": "libDownloader",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libDownloader-2.0.0-SNAPSHOT.aar",
          "url": "libDownloader-2.0.0-SNAPSHOT.aar",
          "size": 112133,
          "sha512": "96d8d5189eae749f416ebaa11dca136743be49a7d39899cde123632635f61615e80fec019d56dffc5917f8c53dbb19f668db5e20765e1a675898c901a46bad7a",
          "sha256": "48a5845fede5116620951eb6a4cf11c30454208bc5de62315844e54ca662d701",
          "sha1": "c88f77557c1fd02cc5465172d26baa3ececbafe4",
          "md5": "d2e7bd8fbf7f48ac9395653a39a60e7c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.koushikdutta.async",
          "module": "androidasync",
          "version": {
            "requires": "2.+"
          }
        },
        {
          "group": "com.arialyy.aria",
          "module": "core",
          "version": {
            "requires": "3.8.15"
          }
        },
        {
          "group": "com.arialyy.aria",
          "module": "ftpComponent",
          "version": {
            "requires": "3.8.15"
          }
        },
        {
          "group": "com.arialyy.aria",
          "module": "sftpComponent",
          "version": {
            "requires": "3.8.15"
          }
        },
        {
          "group": "com.arialyy.aria",
          "module": "m3u8Component",
          "version": {
            "requires": "3.8.15"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libDownloader-2.0.0-SNAPSHOT.aar",
          "url": "libDownloader-2.0.0-SNAPSHOT.aar",
          "size": 112133,
          "sha512": "96d8d5189eae749f416ebaa11dca136743be49a7d39899cde123632635f61615e80fec019d56dffc5917f8c53dbb19f668db5e20765e1a675898c901a46bad7a",
          "sha256": "48a5845fede5116620951eb6a4cf11c30454208bc5de62315844e54ca662d701",
          "sha1": "c88f77557c1fd02cc5465172d26baa3ececbafe4",
          "md5": "d2e7bd8fbf7f48ac9395653a39a60e7c"
        }
      ]
    }
  ]
}
