{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.danmu",
    "module": "libDanmu",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libDanmu-1.0.1-SNAPSHOT.aar",
          "url": "libDanmu-1.0.1-SNAPSHOT.aar",
          "size": 47048,
          "sha512": "c7056a00b81ad02a33208f02b3dc838786c6e531d757dd95a6b109cf1e5a3d3ddf1684973fad64472a51f82f3ad2ed22e8825af569c8d6aef71aecd7eb274beb",
          "sha256": "243f7f061aac50ecd9bc880a2d9da2184272710fdd7f40197f85017c226934e6",
          "sha1": "5f73dfdacd1dd1aa8207fd8dada891b42e27aec4",
          "md5": "c30fa60d91565fe7f42bae3a7420f3d8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libDanmu-1.0.1-SNAPSHOT.aar",
          "url": "libDanmu-1.0.1-SNAPSHOT.aar",
          "size": 47048,
          "sha512": "c7056a00b81ad02a33208f02b3dc838786c6e531d757dd95a6b109cf1e5a3d3ddf1684973fad64472a51f82f3ad2ed22e8825af569c8d6aef71aecd7eb274beb",
          "sha256": "243f7f061aac50ecd9bc880a2d9da2184272710fdd7f40197f85017c226934e6",
          "sha1": "5f73dfdacd1dd1aa8207fd8dada891b42e27aec4",
          "md5": "c30fa60d91565fe7f42bae3a7420f3d8"
        }
      ]
    }
  ]
}
