{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.videocache",
    "module": "libVideoCache",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libVideoCache-1.0.1-SNAPSHOT.aar",
          "url": "libVideoCache-1.0.1-SNAPSHOT.aar",
          "size": 76916,
          "sha512": "8d46cbdd5d97ec754f8a9499c19bf5ece61a414eebe555c610475ddddbc7eb156634b89d5a3479fa47708554fd61b695689c098aa0032ede5bca5202708b7853",
          "sha256": "6ebd56f6858364223122273dab8f730bd033e293f879f1638b8674c80f4dee9d",
          "sha1": "ff7df7a9fa3e97315a000410591378bc4662f712",
          "md5": "938331992ace1bbce475fc82aeddfc54"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.image",
          "module": "libImage",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.basenative",
          "module": "libBaseNative",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "1.0.5-SNAPSHOT"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow-core",
          "version": {
            "requires": "4.2.4"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow",
          "version": {
            "requires": "4.2.4"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "libVideoCache-1.0.1-SNAPSHOT.aar",
          "url": "libVideoCache-1.0.1-SNAPSHOT.aar",
          "size": 76916,
          "sha512": "8d46cbdd5d97ec754f8a9499c19bf5ece61a414eebe555c610475ddddbc7eb156634b89d5a3479fa47708554fd61b695689c098aa0032ede5bca5202708b7853",
          "sha256": "6ebd56f6858364223122273dab8f730bd033e293f879f1638b8674c80f4dee9d",
          "sha1": "ff7df7a9fa3e97315a000410591378bc4662f712",
          "md5": "938331992ace1bbce475fc82aeddfc54"
        }
      ]
    }
  ]
}
