{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.cast",
    "module": "libCast",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCast-2.0.0-SNAPSHOT.aar",
          "url": "libCast-2.0.0-SNAPSHOT.aar",
          "size": 151578,
          "sha512": "fed710a48c2dc985ebda348ecacc797416d5234bde6bac5090771f888e93e68a53dbb03c785e0eef41d685e277a6a677e34f5d297adcc362bed3ff3e37654aef",
          "sha256": "0328c74ba01efeb5dc5aaed76db20fcf03c33b72e7d6b3550a23b165d756d517",
          "sha1": "d91566b3e1f9a12a8dbaa51c439220102c78ac97",
          "md5": "ba04195abafbff967a9c42018f19a278"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.wang.avi",
          "module": "library",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.fourthline.cling",
          "module": "cling-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.fourthline.cling",
          "module": "cling-support",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-server",
          "version": {
            "requires": "8.1.12.v20130726"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-servlet",
          "version": {
            "requires": "8.1.12.v20130726"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-client",
          "version": {
            "requires": "8.1.12.v20130726"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libCast-2.0.0-SNAPSHOT.aar",
          "url": "libCast-2.0.0-SNAPSHOT.aar",
          "size": 151578,
          "sha512": "fed710a48c2dc985ebda348ecacc797416d5234bde6bac5090771f888e93e68a53dbb03c785e0eef41d685e277a6a677e34f5d297adcc362bed3ff3e37654aef",
          "sha256": "0328c74ba01efeb5dc5aaed76db20fcf03c33b72e7d6b3550a23b165d756d517",
          "sha1": "d91566b3e1f9a12a8dbaa51c439220102c78ac97",
          "md5": "ba04195abafbff967a9c42018f19a278"
        }
      ]
    }
  ]
}
