{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.utils",
    "module": "libUtils",
    "version": "1.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-no-op",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow-core",
          "version": {
            "requires": "4.2.4"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow",
          "version": {
            "requires": "4.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "libUtils-1.0.5-SNAPSHOT.aar",
          "url": "libUtils-1.0.5-SNAPSHOT.aar",
          "size": 373532,
          "sha512": "f56b9617c07400b6e9288423d20bf78d49b03b05c4841f94943b2f1b89b6a3346041f5d7e71550d17dce44c0bdef66ddabe66972ad60cf8e4117bfa48697e265",
          "sha256": "a5d6f10c135ae3f57932a1531d4f8e91d1b30efbc0b25caaddc3c02d25a616d9",
          "sha1": "d0bffaed653c7289f4137b43864535ccaf587a50",
          "md5": "4e45c8b3a2b92b6b6d14743a48301495"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-no-op",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow-core",
          "version": {
            "requires": "4.2.4"
          }
        },
        {
          "group": "com.github.Raizlabs.DBFlow",
          "module": "dbflow",
          "version": {
            "requires": "4.2.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "libUtils-1.0.5-SNAPSHOT.aar",
          "url": "libUtils-1.0.5-SNAPSHOT.aar",
          "size": 373532,
          "sha512": "f56b9617c07400b6e9288423d20bf78d49b03b05c4841f94943b2f1b89b6a3346041f5d7e71550d17dce44c0bdef66ddabe66972ad60cf8e4117bfa48697e265",
          "sha256": "a5d6f10c135ae3f57932a1531d4f8e91d1b30efbc0b25caaddc3c02d25a616d9",
          "sha1": "d0bffaed653c7289f4137b43864535ccaf587a50",
          "md5": "4e45c8b3a2b92b6b6d14743a48301495"
        }
      ]
    }
  ]
}
