{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.skin",
    "module": "libSkin",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSkin-1.0.1-SNAPSHOT.aar",
          "url": "libSkin-1.0.1-SNAPSHOT.aar",
          "size": 86198,
          "sha512": "500f90d8076918d994399d07544582ef88376dadcbcf2852f625feadeda411b1caa97829789526b33079f27bd88fb7a7f1bc47248b29da0daa939d9ae7cd7c82",
          "sha256": "e0825e11285d969e246e0f93ca4eab1dd57afc01945e0e9a1bdb1e5f0693dc92",
          "sha1": "772e9970fdd0d44240208061a8d87ea2e119d6ad",
          "md5": "5470541d107e63a5bd5be38f89caaa53"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libSkin-1.0.1-SNAPSHOT.aar",
          "url": "libSkin-1.0.1-SNAPSHOT.aar",
          "size": 86198,
          "sha512": "500f90d8076918d994399d07544582ef88376dadcbcf2852f625feadeda411b1caa97829789526b33079f27bd88fb7a7f1bc47248b29da0daa939d9ae7cd7c82",
          "sha256": "e0825e11285d969e246e0f93ca4eab1dd57afc01945e0e9a1bdb1e5f0693dc92",
          "sha1": "772e9970fdd0d44240208061a8d87ea2e119d6ad",
          "md5": "5470541d107e63a5bd5be38f89caaa53"
        }
      ]
    }
  ]
}
