{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.skin",
    "module": "libSkin",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSkin-1.0.1-SNAPSHOT.aar",
          "url": "libSkin-1.0.1-SNAPSHOT.aar",
          "size": 87050,
          "sha512": "6615cf69807a26d60a3d4af10285b4d7bcf83bba1b71db5eef7c81526799a7072bf57099da9aca91c6f3eb67493e8e0c0048cdec962b29b88d3ae1a8aa63937c",
          "sha256": "b22e6fe42c3ff2995529885690da751e09b2dd8870eb3dbedd392d2ec0ba9f22",
          "sha1": "c7e2b314ac557a232fc09c501a159e244335f8de",
          "md5": "52f55ea65f852b5498215f58ee4fd49e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libSkin-1.0.1-SNAPSHOT.aar",
          "url": "libSkin-1.0.1-SNAPSHOT.aar",
          "size": 87050,
          "sha512": "6615cf69807a26d60a3d4af10285b4d7bcf83bba1b71db5eef7c81526799a7072bf57099da9aca91c6f3eb67493e8e0c0048cdec962b29b88d3ae1a8aa63937c",
          "sha256": "b22e6fe42c3ff2995529885690da751e09b2dd8870eb3dbedd392d2ec0ba9f22",
          "sha1": "c7e2b314ac557a232fc09c501a159e244335f8de",
          "md5": "52f55ea65f852b5498215f58ee4fd49e"
        }
      ]
    }
  ]
}
