{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.basenative",
    "module": "libBaseNative",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libBaseNative-2.0.0-SNAPSHOT.aar",
          "url": "libBaseNative-2.0.0-SNAPSHOT.aar",
          "size": 67141,
          "sha512": "e8b29b4dc7b2ad78bee41c6810401eb4086d04af706250b651f7ecbf49541a3df3cc8d3a6f4dec72d9b22c0f2db6c367907bd0008a7d1d9f4f3444b71f0a6855",
          "sha256": "431c682762d1e493e047d129964a9d0c1313754d81218772f5c998149f4950d8",
          "sha1": "2bced43f36893b8a5adc74abd3d3e18c0b215ab7",
          "md5": "10b656ec36d95d0e1a9d7b3aa7a35366"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseNative-2.0.0-SNAPSHOT.aar",
          "url": "libBaseNative-2.0.0-SNAPSHOT.aar",
          "size": 67141,
          "sha512": "e8b29b4dc7b2ad78bee41c6810401eb4086d04af706250b651f7ecbf49541a3df3cc8d3a6f4dec72d9b22c0f2db6c367907bd0008a7d1d9f4f3444b71f0a6855",
          "sha256": "431c682762d1e493e047d129964a9d0c1313754d81218772f5c998149f4950d8",
          "sha1": "2bced43f36893b8a5adc74abd3d3e18c0b215ab7",
          "md5": "10b656ec36d95d0e1a9d7b3aa7a35366"
        }
      ]
    }
  ]
}
