{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.audio",
    "module": "libAudio",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libAudio-0.0.1-SNAPSHOT.aar",
          "url": "libAudio-0.0.1-SNAPSHOT.aar",
          "size": 20944,
          "sha512": "27d4c6ee7ea145fb13f15990d05773a5b94056620f1b0e033da793a13cf35fcec1f29a5be826ea8c88cf7f1adcd5aca8e02ed0c6824c5a183671ffeadb554e84",
          "sha256": "1e041da438167187da1ca07d6b3e28fc33faada905c0126f8d1891d5db82ecf4",
          "sha1": "db64c7017f26849542ea5263343babc0b5a0e5ef",
          "md5": "5de9280eaed6c60c5c4735cfb710500f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "1.0.10-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libAudio-0.0.1-SNAPSHOT.aar",
          "url": "libAudio-0.0.1-SNAPSHOT.aar",
          "size": 20944,
          "sha512": "27d4c6ee7ea145fb13f15990d05773a5b94056620f1b0e033da793a13cf35fcec1f29a5be826ea8c88cf7f1adcd5aca8e02ed0c6824c5a183671ffeadb554e84",
          "sha256": "1e041da438167187da1ca07d6b3e28fc33faada905c0126f8d1891d5db82ecf4",
          "sha1": "db64c7017f26849542ea5263343babc0b5a0e5ef",
          "md5": "5de9280eaed6c60c5c4735cfb710500f"
        }
      ]
    }
  ]
}
