{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.gradle.classplugin",
    "module": "hive-class-guard",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.3.jar",
          "url": "hive-class-guard-2.0.3.jar",
          "size": 124042,
          "sha512": "bf69e61a5d9a652e5445c9a104789f5454ad359abe42888dc71d5b8144b2eb94d4730ebd61934667915ca4cccf8569a02f7f2c9d9f819ae3b9034aaadad45608",
          "sha256": "d63410aadf51035380b17426a0fd8938515901a5843913839983cef2230ddc54",
          "sha1": "8b30283be44cc80ddbd6780ee2ea7d662d649110",
          "md5": "e392216c6321ad58b7994f53edb32fb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "hive-class-guard-2.0.3.jar",
          "url": "hive-class-guard-2.0.3.jar",
          "size": 124042,
          "sha512": "bf69e61a5d9a652e5445c9a104789f5454ad359abe42888dc71d5b8144b2eb94d4730ebd61934667915ca4cccf8569a02f7f2c9d9f819ae3b9034aaadad45608",
          "sha256": "d63410aadf51035380b17426a0fd8938515901a5843913839983cef2230ddc54",
          "sha1": "8b30283be44cc80ddbd6780ee2ea7d662d649110",
          "md5": "e392216c6321ad58b7994f53edb32fb0"
        }
      ]
    }
  ]
}
