{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.opencv",
    "module": "libOpenCV",
    "version": "2.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libOpenCV-2.0.2-SNAPSHOT.aar",
          "url": "libOpenCV-2.0.2-SNAPSHOT.aar",
          "size": 13583773,
          "sha512": "dff60bd179298fdf2c546e2b602e19b14d5ed5a15460bf7d126b306afb14405077fb2c8bceb626ca6a011ff3a1c810d7a297ef3a1a309197d3aadbc24971aba7",
          "sha256": "937cf91082c23cacd484e298a1fad27f9907046d8dd8548c6d31055e239779a2",
          "sha1": "5643f2be9cf9c6640e0df4ff506922aa36461063",
          "md5": "18a9feab40c331c813ebfe910cdafea0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.views",
          "module": "libViews",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.compon",
          "module": "libCompon",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.image",
          "module": "libImage",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.net",
          "module": "libNet",
          "version": {
            "requires": "2.0.1-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.basenative",
          "module": "libBaseNative",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.hive.base",
          "module": "libBase",
          "version": {
            "requires": "2.0.6-SNAPSHOT"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.takisoft.preferencex",
          "module": "preferencex",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenCV-2.0.2-SNAPSHOT.aar",
          "url": "libOpenCV-2.0.2-SNAPSHOT.aar",
          "size": 13583773,
          "sha512": "dff60bd179298fdf2c546e2b602e19b14d5ed5a15460bf7d126b306afb14405077fb2c8bceb626ca6a011ff3a1c810d7a297ef3a1a309197d3aadbc24971aba7",
          "sha256": "937cf91082c23cacd484e298a1fad27f9907046d8dd8548c6d31055e239779a2",
          "sha1": "5643f2be9cf9c6640e0df4ff506922aa36461063",
          "md5": "18a9feab40c331c813ebfe910cdafea0"
        }
      ]
    }
  ]
}
