{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hive.basenative",
    "module": "libBaseNative",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libBaseNative-1.0.3-SNAPSHOT.aar",
          "url": "libBaseNative-1.0.3-SNAPSHOT.aar",
          "size": 67235,
          "sha512": "be9f5f2879d2670fc85cb94b90b0b3767e7989df958bf73f722bd84c0d961a6b5d0840775f4e7a25ffd4c7dc5fd6f968762af2fed3b086ac1343f297fb979a40",
          "sha256": "90ed722333d715e68fea5f46b5aa34c1858aa62c5b22920a155c7985588776d8",
          "sha1": "02f0fa351bd2f0a7fe9ed67ee115a52f5175ff04",
          "md5": "e58d903218bdb634a09033187d5ecbc1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "com.hive.utils",
          "module": "libUtils",
          "version": {
            "requires": "1.0.6-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseNative-1.0.3-SNAPSHOT.aar",
          "url": "libBaseNative-1.0.3-SNAPSHOT.aar",
          "size": 67235,
          "sha512": "be9f5f2879d2670fc85cb94b90b0b3767e7989df958bf73f722bd84c0d961a6b5d0840775f4e7a25ffd4c7dc5fd6f968762af2fed3b086ac1343f297fb979a40",
          "sha256": "90ed722333d715e68fea5f46b5aa34c1858aa62c5b22920a155c7985588776d8",
          "sha1": "02f0fa351bd2f0a7fe9ed67ee115a52f5175ff04",
          "md5": "e58d903218bdb634a09033187d5ecbc1"
        }
      ]
    }
  ]
}
